name: Merge JSON Updates to Main

permissions:
  contents: write

on:
  schedule:
    - cron: "20 12 * * *"  # 8:20 AM ET (EDT) / 7:20 AM ET (EST)
    - cron: "20 0 * * *"   # 8:20 PM ET (EDT) / 7:20 PM ET (EST)
  workflow_dispatch:

concurrency:
  group: merge-json-updates
  cancel-in-progress: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fast-forward main to json-updates if ahead
        shell: bash
        run: |
          set -euo pipefail
          git fetch --prune origin

          # Exit if either branch is missing
          git rev-parse --verify -q origin/main >/dev/null || exit 0
          git rev-parse --verify -q origin/json-updates >/dev/null || exit 0

          MAIN=origin/main
          UP=origin/json-updates

          # No differences? Done.
          git diff --quiet "$MAIN" "$UP" && { echo "No changes."; exit 0; }

          # Only merge when it's a true fast-forward (no merge commit)
          if git merge-base --is-ancestor "$MAIN" "$UP"; then
            UP_SHA=$(git rev-parse "$UP")
            echo "Fast-forwarding main -> $UP_SHA"
            git push origin "$UP_SHA:refs/heads/main"
          else
            echo "Histories diverged; skipping to protect main."
          fi
